FROM rust:1.91 AS builder
WORKDIR /usr/src/app
COPY . .
RUN --mount=type=cache,target=/usr/local/cargo,from=rust:1.91,source=/usr/local/cargo \
    --mount=type=cache,target=target \
    cargo build

FROM debian:trixie-slim
COPY --from=builder /usr/src/app/target/debug/llm_worker /usr/local/bin/llm_worker

EXPOSE 3042
CMD ["llm_worker"]
