FROM oven/bun:1 AS base
WORKDIR /usr/src/app

COPY package.json bun.lock /usr/src/app/
RUN bun install --frozen-lockfile

COPY . .
RUN bun run build

ENV NEXT_TELEMETRY_DISABLED=1
EXPOSE 3000/tcp
ENTRYPOINT [ "bun", "--bun", "run", "dev" ]